export enum DateFormat {
  ISO_STRING = 'YYYY-MM-DDTHH:mm:ss.sssZ',
  ISO_STRING_NOT_TZ = 'YYYY-MM-DDTHH:mm:ss.SSS',
  DD_MM_YYYY = 'DD/MM/YYYY',
  DD_MMM_YYYY_WITH_SPACE = 'DD MMM YYYY',
  LT = 'LT',
  DATE_TIME_IMPORT_TRIP = 'YYYY-MM-DDTHH:mm',
  FULL_DATE_TIME = 'YYYY-MM-DD HH:mm:ss',
  FULL_DATE_HYPHEN = 'YYYY-MM-DD',
  INVOICE_NUMBER_FORMAT = 'YYYYMMDD',
}
